account_id = "cbc913441ab0886aa2acc96be25aa6ae"
name = "users-demo"
type = "javascript"
route = "users-demo.ajderha.com/*"
workers_dev = false
zone_id = "67b2303fa055f4aa0611129b2951593c"

[site]
bucket = "dist"
entry-point = "workers-site"
